{% set version = "0.4.0" %}
package:
  name: feather-format
  version: {{ version }}

source:
  fn: feather-format-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/f/feather-format/feather-format-{{ version }}.tar.gz
  md5: e5bc36af8a2bdbe34a0af2a602b7c1b8

build:
  number: 1
  skip: true  # [win32]
  skip: true  # [win and py<35]
  features:
    - vc14  # [win and py>=35]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pandas >=0.19.2
    - pyarrow

test:
  imports:
    - feather

about:
  home: https://github.com/wesm/feather
  license: Apache 2.0
  summary: "Feather: fast, interoperable binary data frame storage for Python, R, and more powered by Apache Arrow"

extra:
  recipe-maintainers:
    - jjhelmus
    - msarahan
    - wesm
    - cpcloud
    - jreback
