{% set version = "0.3.1" %}
package:
  name: feather-format
  version: {{ version }}

source:
  fn: feather-format-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/f/feather-format/feather-format-{{ version }}.tar.gz
  md5: 0b34d70b1ba1226813ed879a9c2ddcbc

build:
  number: 1
  skip: true  # [win and py<35]

requirements:
  build:
    - python
    - setuptools
    - cython
    - pandas >=0.17.0
  run:
    - python
    - pandas >=0.17.0
    - vs2015_runtime  # [win]

test:
  imports:
    - feather

about:
  home: https://github.com/wesm/feather
  license: Apache 2.0
  summary: "Feather: fast, interoperable binary data frame storage for Python, R, and more powered by Apache Arrow"

extra:
  recipe-maintainers:
    - jjhelmus
    - msarahan
    - wesm
