package:
  name: feather-format
  version: git_master

source:
  git_url: https://github.com/wesm/feather.git
  git_rev: master

build:
  number: 0
  msvc_compiler: 14.0  # [win]

requirements:
  build:
    - python
    - setuptools
    - cython
    - pandas >=0.17.0
  run:
    - python
    - pandas >=0.17.0
    - vs2015_runtime  # [win]

test:
  imports:
    - feather

about:
  home: https://github.com/wesm/feather 
  license: Apache 2.0
  summary: "Feather: fast, interoperable binary data frame storage for Python, R, and more powered by Apache Arrow"

extra:
  recipe-maintainers:
    - jjhelmus
    - msarahan
